CREATE TABLE bicycles
(
    id        INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30) NOT NULL,
    price     FLOAT,
    supplier_id INT(6) UNSIGNED,
    battery_id INT(6) UNSIGNED,
    type_id INT(6) UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE features
(
    id        INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30) NOT NULL,
    bicycle_id INT(6) UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE suppliers
(
    id        INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE batteries
(
    id        INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE types
(
    id        INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
